### ISSUE TITLE
add instant ranking in app

### ISSUE THREAD

**Issue by jakobj** [jakobj/kicker_league#19]

**Comment by jakobj** [comment]
this issue is related to creating a new screen which shows a ranking of players according to their strength.

**Comment by mschmidt87** [comment]
addressed by #38 .

Currently, the ranking is called via the ranking button from the home screen, but we would like to implement the ranking as an additional tab of the home screen so that the user can access by wiping to the right/left.

**Comment by jakobj** [comment]
in addition it would be great to somehow highlight changes in the ranking. maybe displaying an arrow up/arrow down, if the player has moved a position up/down compared to the last day? could we add more information, like total number of wins or games to the table or is it too cluttered then?

**Comment by mschmidt87** [comment]
Yes, we could display changes in the ranking, but for that we would need to send information on the past rank by the web service. The web service would need a function which computes ELO numbers for a certain time range. This is connected to #40.

The other request is also possible, but again the web service would need to be changed to send more information on the player, i.e. number of wins and losses. This is connected to #39 .

**Comment by mschmidt87** [comment]
We currently have the problem that there is no refreshing possible in the ranking. 
It would be nice to synchronize refreshments in the home screen and ranking, so that whenever the user refreshes the home screen, the ranking is refreshed as well. This requires a major re-design of the whole activity and fragments.

Another, more easier, approach (could also be done in addition to the previous idea) would be to implement the swipe refresh in the ranking as well.

**Comment by jakobj** [comment]
i have now implemented the refresh in such a way, that on every fragment change (i.e., swipe) refresh() is called. this keeps both fragments more or less up to date. how ever the problem still remains in the case when someone is just staying on the ranking screen for a long time. then the score will still be outdated.
